version: '3'
services:
  app:
    build:
      context: ./php
    volumes:
      - './../:/var/www/html'
      - './data/sites:/etc/apache2/sites-available'
      - './data/LOGS:/var/www/logs'
      - './data/root:/root'

